{
    "sbt_version": 1,
    "mesh_fineness": 0,
    "HYPERPARAM1": 0,
    "HYPERPARAM2": "MassFlowRate.xlsx",
    "HYPERPARAM3": 0,
    "HYPERPARAM4": "InjectionTemperatures.xlsx",
    "HYPERPARAM5": None,
    "accuracy": 1,
    "clg_configuration": 2,
    "mdot": 100,
    "Tinj": 30.0,
    "fluid": 1,
    "DrillingDepth_L1": 5.0,
    "HorizontalExtent_L2": 2.5,
    "Diameter1": 0.35,
    "Diameter2": 0.35,
    "PipeParam3": 1,
    "PipeParam4": [1],
    "PipeParam5": 1,
    "Tsurf": 25,
    "GeoGradient": 0.06,
    "k_m": 3,
    "c_m": 790,
    "rho_m": 2750,
}
